fix: fixing mising keystore in github workflow to automate

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -69,6 +69,21 @@ jobs:
       ##########################################################
       ## Build Release APK
       ##########################################################
+      - name: Decode Release Keystore
+        run: |
+          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > merchgo-release.jks
+
+      - name: Create keystore.properties
+        run: |
+          printf "STORE_FILE=merchgo-release.jks\nSTORE_PASSWORD=%s\nKEY_ALIAS=%s\nKEY_PASSWORD=%s\n" \
+            "${{ secrets.STORE_PASSWORD }}" \
+            "${{ secrets.KEY_ALIAS }}" \
+            "${{ secrets.KEY_PASSWORD }}" > keystore.properties
+
+      - name: Verify signing files
+        run: |
+          ls -lh
+          cat keystore.properties
 
       - name: Build Release APK
         run: |
@@ -128,9 +143,14 @@ jobs:
       - name: Rename APK
         run: |
           mkdir -p release
-
-          APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
-
+          
+          APK=$(find app/build/outputs/apk/release -type f -name "*.apk" | head -n 1)
+          
+          if [ -z "$APK" ]; then
+            echo "APK not found!"
+            exit 1
+          fi
+          
           cp "$APK" "release/MerchGo-${{ steps.tag.outputs.new_tag }}.apk"
 
       ##########################################################
@@ -152,4 +172,5 @@ jobs:
         with:
           tag_name: ${{ steps.tag.outputs.new_tag }}
           generate_release_notes: true
+          overwrite_files: true
           files: release/*.apk
